// Image asset map for lawyer.id.vn
// Auto-generated from assets.json (Nano Banana 2 image generation)
// Usage: import { IMAGES } from "@/lib/images";

export const IMAGES = {
  heroHome: {
    id: 'hero-home',
    name: 'Homepage Hero — HCMC Skyline from Office',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/hero-home-9a98774e.webp',
    alt: 'Modern law office overlooking Ho Chi Minh City skyline at golden hour',
    width: 1920,
    aspect: '16:9',
  },
  heroAboutPortrait: {
    id: 'hero-about-portrait',
    name: 'About Page Hero — Attorney Portrait',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/hero-about-portrait-043e86a0.webp',
    alt: 'Henry Vo (Vo Thien Hien) — International Lawyer in Vietnam',
    width: 1920,
    aspect: '16:9',
  },
  heroInternationalClients: {
    id: 'hero-international-clients',
    name: 'International Clients Section Hero',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/hero-international-clients-afb2eea8.webp',
    alt: 'Modern international law firm conference room overlooking HCMC',
    width: 1600,
    aspect: '16:9',
  },
  ogDefault: {
    id: 'og-default',
    name: 'OG Card — Default',
    category: 'og',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/og/og-default-760157f0.webp',
    alt: 'Henry Vo — International Lawyer in Vietnam',
    width: 1200,
    aspect: '1200:630',
  },
  iconScales: {
    id: 'icon-scales',
    name: 'Scales of Justice',
    category: 'icon',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/icon/icon-scales-fece7b9a.webp',
    alt: 'Scales of Justice',
    width: 1024,
    aspect: '1:1',
  },
  iconGavel: {
    id: 'icon-gavel',
    name: 'Gavel',
    category: 'icon',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/icon/icon-gavel-7c512f4b.webp',
    alt: 'Gavel',
    width: 1024,
    aspect: '1:1',
  },
  iconGlobe: {
    id: 'icon-globe',
    name: 'World Globe with Meridians',
    category: 'icon',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/icon/icon-globe-bf1be779.webp',
    alt: 'World globe representing international practice',
    width: 1024,
    aspect: '1:1',
  },
  iconContract: {
    id: 'icon-contract',
    name: 'Contract and Pen',
    category: 'icon',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/icon/icon-contract-c1b3320d.webp',
    alt: 'Contract document with pen',
    width: 1024,
    aspect: '1:1',
  },
  iconHandshake: {
    id: 'icon-handshake',
    name: 'Handshake (Client Partnership)',
    category: 'icon',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/icon/icon-handshake-910b9149.webp',
    alt: 'Handshake symbolizing attorney-client partnership',
    width: 1024,
    aspect: '1:1',
  },
  iconFavicon: {
    id: 'icon-favicon',
    name: 'Favicon — Mini Scales',
    category: 'icon',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/icon/icon-favicon-b008b699.webp',
    alt: 'lawyer.id.vn favicon',
    width: 512,
    aspect: '1:1',
  },
  bgOfficeTexture: {
    id: 'bg-office-texture',
    name: 'Subtle Office Background Texture',
    category: 'background',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/background/bg-office-texture-de13c103.webp',
    alt: '',
    width: 1920,
    aspect: '16:9',
  },

  // ====== PRACTICE-AREA HEROES, INFOGRAPHICS, ORNAMENTS ======
  practiceCivilLitigation: {
    id: 'practice-civil-litigation-hero',
    name: 'Practice Hero — Civil Litigation',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-civil-litigation-hero-6fdc55d4.webp',
    alt: 'Vietnamese courtroom interior',
    width: 1600,
    aspect: '16:9',
  },
  practiceLandProperty: {
    id: 'practice-land-property-hero',
    name: 'Practice Hero — Land & Property',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-land-property-hero-14d4e92e.webp',
    alt: 'HCMC residential development at golden hour',
    width: 1600,
    aspect: '16:9',
  },
  practiceFamilyDivorce: {
    id: 'practice-family-divorce-hero',
    name: 'Practice Hero — Family Law & Divorce',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-family-divorce-hero-5fff892a.webp',
    alt: 'Family law consultation',
    width: 1600,
    aspect: '16:9',
  },
  practiceCorporate: {
    id: 'practice-corporate-hero',
    name: 'Practice Hero — Corporate & Commercial',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-corporate-hero-af96e83d.webp',
    alt: 'Modern corporate office building HCMC',
    width: 1600,
    aspect: '16:9',
  },
  practiceLaborEmployment: {
    id: 'practice-labor-employment-hero',
    name: 'Practice Hero — Labor & Employment',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-labor-employment-hero-b70bb84a.webp',
    alt: 'Cross-cultural business handshake',
    width: 1600,
    aspect: '16:9',
  },
  practiceCriminalDefense: {
    id: 'practice-criminal-defense-hero',
    name: 'Practice Hero — Criminal Defense',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-criminal-defense-hero-e5f66da3.webp',
    alt: 'Vietnamese courthouse exterior at twilight',
    width: 1600,
    aspect: '16:9',
  },
  practiceArbitration: {
    id: 'practice-arbitration-hero',
    name: 'Practice Hero — International Arbitration',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-arbitration-hero-11f50a5d.webp',
    alt: 'International arbitration hearing room',
    width: 1600,
    aspect: '16:9',
  },
  practiceOverview: {
    id: 'practice-overview-hero',
    name: 'Practice Hero — Overview',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/practice-overview-hero-30afe367.webp',
    alt: 'Legal documents and antique gold pen',
    width: 1600,
    aspect: '16:9',
  },
  infographicCourtSystem: {
    id: 'infographic-court-system',
    name: 'Vietnam Court System Infographic',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/infographic-court-system-96144862.webp',
    alt: 'Vietnam court system hierarchy',
    width: 1200,
    aspect: '16:9',
  },
  infographicDisputeResolution: {
    id: 'infographic-dispute-resolution',
    name: 'Dispute Resolution Decision Tree',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/infographic-dispute-resolution-dd0fd788.webp',
    alt: 'Dispute resolution pathways in Vietnam',
    width: 1200,
    aspect: '16:9',
  },
  bgSectionDivider1: {
    id: 'bg-section-divider-1',
    name: 'Section Divider — Gold Lines',
    category: 'background',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/background/bg-section-divider-1-772d6688.webp',
    alt: '',
    width: 1920,
    aspect: '21:9',
  },
  bgSectionDivider2: {
    id: 'bg-section-divider-2',
    name: 'Section Divider — Topographic',
    category: 'background',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/background/bg-section-divider-2-82282ad6.webp',
    alt: '',
    width: 1920,
    aspect: '16:9',
  },
  bgPatternMeridians: {
    id: 'bg-pattern-meridians',
    name: 'Decorative Pattern — Meridians',
    category: 'background',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/background/bg-pattern-meridians-106fd87e.webp',
    alt: '',
    width: 1600,
    aspect: '16:9',
  },
  caseCrossBorderFlow: {
    id: 'case-cross-border-flow',
    name: 'Case Visual — Cross-Border Connections',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/case-cross-border-flow-c2916624.webp',
    alt: 'Cross-border legal connections worldwide',
    width: 1200,
    aspect: '3:2',
  },
  caseDocumentSigning: {
    id: 'case-document-signing',
    name: 'Case Visual — Document Signing',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/case-document-signing-4fdb5944.webp',
    alt: 'Hands signing legal document',
    width: 1200,
    aspect: '3:2',
  },
  articleHeroInvestor: {
    id: 'article-hero-investor',
    name: 'Article Hero — For Investors',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/article-hero-investor-ba01593f.webp',
    alt: 'International investor reviewing documents',
    width: 1200,
    aspect: '16:9',
  },
  articleHeroExpat: {
    id: 'article-hero-expat',
    name: 'Article Hero — For Expats',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/article-hero-expat-2cdb278e.webp',
    alt: 'Expat walking in District 1 HCMC',
    width: 1200,
    aspect: '16:9',
  },

  // ====== ABOUT-PAGE IMAGES (Mr Hiển image-to-image series) ======
  aboutHeroCinematic: {
    id: 'about-hero-cinematic',
    name: 'About Hero — Cinematic Office Portrait of Mr Hiển',
    category: 'hero',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/hero/about-hero-cinematic-1963dd1f.webp',
    alt: 'Mr Hiển in his Ho Chi Minh City law office at golden hour',
    width: 1920,
    aspect: '16:9',
  },
  aboutMrHienDesk: {
    id: 'about-mr-hien-desk',
    name: 'About — Mr Hiển at Desk',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/about-mr-hien-desk-bd4a1f21.webp',
    alt: 'Mr Hiển reviewing legal documents at his desk',
    width: 1600,
    aspect: '3:2',
  },
  aboutMrHienBookshelf: {
    id: 'about-mr-hien-bookshelf',
    name: 'About — Mr Hiển at Law Library',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/about-mr-hien-bookshelf-2c088245.webp',
    alt: 'Mr Hiển at the law library bookshelf',
    width: 1600,
    aspect: '3:2',
  },
  aboutMrHienMeeting: {
    id: 'about-mr-hien-meeting',
    name: 'About — Mr Hiển in Client Consultation',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/about-mr-hien-meeting-0de7fb66.webp',
    alt: 'Mr Hiển consulting with a client',
    width: 1600,
    aspect: '3:2',
  },
  aboutMrHienWalking: {
    id: 'about-mr-hien-walking',
    name: 'About — Mr Hiển Walking in District 1',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/about-mr-hien-walking-3f32c261.webp',
    alt: 'Mr Hiển walking along a District 1 boulevard',
    width: 1600,
    aspect: '3:2',
  },
  aboutMrHienSpeaking: {
    id: 'about-mr-hien-speaking',
    name: 'About — Mr Hiển Speaking at Conference',
    category: 'content',
    cdn: 'https://pub-ebe397ad6fc946888f5c9aacc3cc48bb.r2.dev/lawyer.id.vn/content/about-mr-hien-speaking-6c193131.webp',
    alt: 'Mr Hiển at the lectern during a conference',
    width: 1600,
    aspect: '3:2',
  },
} as const

export type ImageId = keyof typeof IMAGES
